### PR TITLE
NFDHCPDFILECONTENTS -> NFDHCPD_STATE_EXTRA, write nfdhcpd bindings with here-doc

### PR DESCRIPTION
**Pull request by zmousm**
Ensure that what is appended to $FILECONTENTS does not go on the same
line as $NFDHCPDFILECONTENTS value.

### CODE REVIEW

**Comment by skalkoto** [comment]
Hello, I've checked the `setup_nfdhcpd` function. There is a potential bug if the `NFDHCPDFILECONTENTS` variable does not contain a new line at the end and what you propose really solves the problem but I'm not sure that  this is the cleanest thing to do. The code looks strange before your contribution and will look even stranger after it.

Using a here-document (http://tldp.org/LDP/abs/html/here-docs.html) makes more sense to me:
```
function setup_nfdhcpd {                                                        
  if [ -f /etc/default/nfdhcpd ]; then                                          
    umask 022                                                                   
    source /etc/default/nfdhcpd                                                 
                                                                                
    if [ "$DISABLE_IPV4" == "1" ]; then                                         
      local NETWORK_SUBNET=''                                                   
      local IP=''                                                               
    fi                                                                          
                                                                                
    if [ "$DISABLE_IPV6" == "1" ]; then                                         
      local NETWORK_SUBNET6=''                                                  
      local EUI64=''                                                            
    fi                                                                          
                                                                                
    cat > $NFDHCPD_STATE_DIR/$INTERFACE  <<EOF
$NFDHCPDFILECONTENTS
INDEV=$INDEV                                                 
IP=$IP                                                                          
MAC=$MAC                                                                        
HOSTNAME=$INSTANCE                                                              
TAGS=\"$TAGS\"                                                                  
GATEWAY=$NETWORK_GATEWAY                                                        
SUBNET=$NETWORK_SUBNET                                                          
GATEWAY6=$NETWORK_GATEWAY6                                                      
SUBNET6=$NETWORK_SUBNET6                                                        
EUI64=$EUI64
EOF                                                                  
}
```
This way you reduce the number of if...else, you do not need to check if a variable ends with `$'\n'` which by the way is not very common and you can easily recognize the format of the file.

By the way, NFDHCPDFILECONTENTS is not documented anywhere. If it is used it should probably have a commented out default value in defaults.in. The name is also a little bit strange: `NFDHCPD_STATE_HEAD` of `NFDHCPD_STATE_PREFIX`are IMHO better names.

@kargig @irregulator what do you think?

**Comment by zmousm** [comment]
I agree with all remarks by @skalkoto. I shall update the patch.

**Comment by skalkoto** [comment]
You don't escape `"` in here-documents. The TAGS line should be like this:
```
TAGS="$TAGS"
```
my mistake

**Comment by zmousm** [comment]
On a second thought, while I agree to the simplicity afforded by the here-doc approach, this will add an empty line at the top of this file when (most commonly) the variable is not set. I thus opt for a small tweak there; I can remove it if you don't like it.

**Comment by skalkoto** [comment]
I don't think that having an extra new line in some cases matters. Keeping the code simple is more important.

When changing `NFDHCPDFILECONTENTS` to `NFDHCPD_STATE_EXTRA` we probably need some deprecation period. If `NFDHCPDFILECONTENTS` is set and not `NFDHCPD_STATE_EXTRA` then we should probably copy `NFDHCPDFILECONTENTS` to `NFDHCPD_STATE_EXTRA` and create a deprecation warning.

Also, having 4 commits for this is an overkill. It's better if you merge the changes into 1 or 2 (one for the refinement and one for the renaming of the variable) commits.

**Comment by zmousm** [comment]
OK, as you wish.

**Comment by skalkoto** [comment]
Merged the commits to the repo. Just changed a little bit the commit messages to comply to the 50/72 Formatting rule. https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting

**Comment by zmousm** [comment]
I do follow that convention, but I'm willing to break the first rule if necessary.

**Pull request closed without merging**
